language: ruby

cache: bundler

sudo: false

rvm: 2.3.3

notifications:
  email: false

before_install:
- openssl aes-256-cbc -K $encrypted_3934c5b080f0_key -iv $encrypted_3934c5b080f0_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval `ssh-agent`
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

install:
- script/bootstrap

script:
- script/cibuild

deploy:
- provider: script
  script: script/deploy
  on:
    branch: master
