title: Imperial College Christian Union
author: Imperial College Christian Union
email: cu@imperial.ac.uk
description: >
  The Christian Union at Imperial College London is a student society which aims
  to give every student at Imperial an opportunity to hear about and respond to
  the good news of Jesus Christ.
baseurl: ""
url: ""
twitter_username: CU_Imperial
#github_username:  Imperial-CU
instagram_username: ic_christian_union
facebook_username: imperialcu
youtube_username: imperialcu
social:
  name: Imperial College Christian Union
  links:
    - https://twitter.com/CU_Imperial
    - https://www.facebook.com/imperialcu
    - https://instagram.com/ic_christian_union

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg


include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

