# SITE CONFIGURATION
title: Hsuile # your site title
author: Hsuile # You :P
description: > # Meta description of Homepage
  Website in progress.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hsuile.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
#social:
  #name: Your Name
  #links:
  #  - https://twitter.com/BenBalter
  #  - https://www.facebook.com/ben.balter
  #  - https://www.linkedin.com/in/BenBalter
  #  - https://plus.google.com/+BenBalter
  #  - https://github.com/benbalter
  #  - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Services', link: '/services'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
#  - {name: 'Blog', link: '/blog'}

tagline: >
  Currently being built.

hero_img: posts/dallas-reedy-9ibcYkU_rSk-unsplash.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: shyuileh@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
